insert into EXCHANGE(ID,TABLE_FROM,TABLE_TO,CONVERTION_MULTIPLE,ENVIRONMENT_VARIABLE) values(1001,'USA','INR',40,'400');
insert into EXCHANGE(ID,TABLE_FROM,TABLE_TO,CONVERTION_MULTIPLE,ENVIRONMENT_VARIABLE) values(1002,'AUD','INR',50,'500');
insert into EXCHANGE(ID,TABLE_FROM,TABLE_TO,CONVERTION_MULTIPLE,ENVIRONMENT_VARIABLE) values(1003,'South','INR',60,'600');
insert into EXCHANGE(ID,TABLE_FROM,TABLE_TO,CONVERTION_MULTIPLE,ENVIRONMENT_VARIABLE) values(1004,'NIG','INR',70,'700');
